/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import * as path from 'path';
import { Duration } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as events from 'aws-cdk-lib/aws-events';
import * as targets from 'aws-cdk-lib/aws-events-targets';
import { Runtime, Architecture } from 'aws-cdk-lib/aws-lambda';
import * as lambda from 'aws-cdk-lib/aws-lambda-nodejs';
import { NagSuppressions } from 'cdk-nag';
import { Construct } from 'constructs';

/** Reconciler Lambda timeout (minutes). */
const RECONCILER_TIMEOUT_MINUTES = 5;

/** Default reconciliation schedule interval (minutes). */
const DEFAULT_SCHEDULE_MINUTES = 15;

/** Reconciler Lambda memory (MB). */
const RECONCILER_MEMORY_MB = 256;

/**
 * Properties for ConcurrencyReconciler construct.
 */
export interface ConcurrencyReconcilerProps {
  /**
   * The DynamoDB task table (has UserStatusIndex GSI).
   */
  readonly taskTable: dynamodb.ITable;

  /**
   * The DynamoDB user concurrency table.
   */
  readonly userConcurrencyTable: dynamodb.ITable;

  /**
   * How often to run the reconciler.
   * @default Duration.minutes(15)
   */
  readonly schedule?: Duration;
}

/**
 * Scheduled Lambda that reconciles user concurrency counters by comparing
 * the active_count in the concurrency table against actual active tasks
 * in the task table. Corrects drift caused by orchestrator crashes.
 */
export class ConcurrencyReconciler extends Construct {
  public readonly fn: lambda.NodejsFunction;

  constructor(scope: Construct, id: string, props: ConcurrencyReconcilerProps) {
    super(scope, id);

    const handlersDir = path.join(__dirname, '..', 'handlers');

    this.fn = new lambda.NodejsFunction(this, 'ReconcilerFn', {
      entry: path.join(handlersDir, 'reconcile-concurrency.ts'),
      handler: 'handler',
      runtime: Runtime.NODEJS_24_X,
      architecture: Architecture.ARM_64,
      timeout: Duration.minutes(RECONCILER_TIMEOUT_MINUTES),
      memorySize: RECONCILER_MEMORY_MB,
      environment: {
        TASK_TABLE_NAME: props.taskTable.tableName,
        USER_CONCURRENCY_TABLE_NAME: props.userConcurrencyTable.tableName,
      },
      bundling: {
        externalModules: ['@aws-sdk/*'],
      },
    });

    props.taskTable.grantReadData(this.fn);
    props.userConcurrencyTable.grantReadWriteData(this.fn);

    const schedule = props.schedule ?? Duration.minutes(DEFAULT_SCHEDULE_MINUTES);
    const rule = new events.Rule(this, 'ReconcilerSchedule', {
      schedule: events.Schedule.rate(schedule),
    });
    rule.addTarget(new targets.LambdaFunction(this.fn));

    NagSuppressions.addResourceSuppressions(this.fn, [
      {
        id: 'AwsSolutions-IAM4',
        reason: 'AWSLambdaBasicExecutionRole is required for CloudWatch Logs access',
      },
      {
        id: 'AwsSolutions-IAM5',
        reason: 'DynamoDB index/* wildcards generated by CDK grantReadData/grantReadWriteData',
      },
    ], true);
  }
}
