/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import { RemovalPolicy } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';

/**
 * Properties for JiraWorkspaceRegistryTable construct.
 */
export interface JiraWorkspaceRegistryTableProps {
  /**
   * Optional table name override.
   * @default - auto-generated by CloudFormation
   */
  readonly tableName?: string;

  /**
   * Removal policy for the table.
   * @default RemovalPolicy.DESTROY
   */
  readonly removalPolicy?: RemovalPolicy;

  /**
   * Whether to enable point-in-time recovery.
   * @default true
   */
  readonly pointInTimeRecovery?: boolean;
}

/**
 * DynamoDB table tracking Jira Cloud tenants that have completed OAuth onboarding.
 *
 * Schema: jira_cloud_id (PK) — Atlassian's tenant identifier (UUID), the stable
 * key returned from `accessible-resources` and present on every webhook payload.
 *
 * Fields:
 * - site_url — `https://<your-domain>.atlassian.net` (display only; NOT a
 *   valid REST base for the 3LO token, which is minted with
 *   `audience=api.atlassian.com` and must call the
 *   `https://api.atlassian.com/ex/jira/<cloudId>` gateway base instead)
 * - oauth_secret_arn — full ARN of the per-tenant Secrets Manager secret
 *   (`bgagent-jira-oauth-<cloudId>`) holding the OAuth bundle (access/refresh
 *   tokens, client credentials, and the webhook signing secret). Created by
 *   `bgagent jira setup`, not by CDK.
 * - installed_by_platform_user_id — Cognito sub of the admin who ran
 *   `bgagent jira setup` (audit only; runtime callers do not need this)
 * - installed_at, updated_at — ISO timestamps
 * - status — 'active' | 'revoked'
 *
 * The webhook receiver, processor, and orchestrator look up `oauth_secret_arn`
 * here from the inbound webhook's `cloudId`, then fetch (and, on the Lambda
 * paths, refresh) the tenant's OAuth/signing secret from Secrets Manager —
 * see `jira-oauth-resolver.ts`. Token sharing is intentional: one
 * bgagent[bot] identity per tenant, used for all members' triggered tasks
 * (parity with the Linear adapter).
 */
export class JiraWorkspaceRegistryTable extends Construct {
  /**
   * The underlying DynamoDB table.
   */
  public readonly table: dynamodb.Table;

  constructor(scope: Construct, id: string, props: JiraWorkspaceRegistryTableProps = {}) {
    super(scope, id);

    this.table = new dynamodb.Table(this, 'Table', {
      tableName: props.tableName,
      partitionKey: {
        name: 'jira_cloud_id',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: props.pointInTimeRecovery ?? true,
      },
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
    });
  }
}
