/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import { RemovalPolicy } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';

/**
 * Properties for TaskEventsTable construct.
 */
export interface TaskEventsTableProps {
  /**
   * Optional table name override.
   * @default - auto-generated by CloudFormation
   */
  readonly tableName?: string;

  /**
   * Removal policy for the table.
   * @default RemovalPolicy.DESTROY
   */
  readonly removalPolicy?: RemovalPolicy;

  /**
   * Whether to enable point-in-time recovery.
   * @default true
   */
  readonly pointInTimeRecovery?: boolean;
}

/**
 * DynamoDB table for the append-only task events audit log.
 *
 * Schema: task_id (PK) + event_id (SK, ULID).
 * Each item represents a lifecycle event (task_created, session_started,
 * task_completed, etc.) with a timestamp and optional metadata.
 * ULIDs provide chronological sort order within each task.
 */
export class TaskEventsTable extends Construct {
  /**
   * The underlying DynamoDB table. Use this to grant access or read the table name.
   */
  public readonly table: dynamodb.Table;

  constructor(scope: Construct, id: string, props: TaskEventsTableProps = {}) {
    super(scope, id);

    this.table = new dynamodb.Table(this, 'Table', {
      tableName: props.tableName,
      partitionKey: {
        name: 'task_id',
        type: dynamodb.AttributeType.STRING,
      },
      sortKey: {
        name: 'event_id',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      timeToLiveAttribute: 'ttl',
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: props.pointInTimeRecovery ?? true,
      },
      // DynamoDB Streams feed the Phase 1b fan-out plane (Slack, GitHub comments,
      // email) via a Lambda subscriber. NEW_IMAGE is sufficient — consumers only
      // need the event payload, not old/new diffs. Enabling Streams on an existing
      // table is an in-place CloudFormation update (no table replacement).
      //
      // CONSUMER BUDGET (Chunk 8 architectural note): this stream currently
      // has TWO consumers: `FanOutConsumer` (Slack / GitHub / email dispatch)
      // and `ApprovalMetricsPublisherConsumer` (Cedar-HITL EMF emission for
      // the CloudWatch dashboard widgets in §11.3). DynamoDB Streams are
      // designed for up to 2 concurrent consumers per shard before throughput
      // degrades. Any future third consumer should migrate this table to
      // **Kinesis Data Streams for DynamoDB** (opt-in, different API) rather
      // than stacking a third `DynamoEventSource` on the legacy Streams
      // interface. Adding a third Lambda here without that migration will
      // silently degrade fanout + metrics latency for the whole stack.
      stream: dynamodb.StreamViewType.NEW_IMAGE,
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
    });
  }
}
